In [7]:
from ultralytics import YOLO
model = YOLO("yolov8s-pose.pt")
results = model('screen.png', save=True)


image 1/1 d:\magisterka\is_project\screen.png: 640x448 1 person, 485.0ms
Speed: 4.0ms preprocess, 485.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 448)
Results saved to runs\pose\predict3


In [2]:
import numpy as np

# Tworzenie przykładowego numpy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

# Określ, ile elementów ma być w każdym zbiorze (w tym przypadku 3)
n = 3

# Oblicz liczbę pełnych zbiorów o długości n
num_sets = len(arr) // n

# Obcinamy array do wielokrotności n, pomijając resztę elementów
arr = arr[:num_sets * n]

# Podziel array na zbiory o n elementach
splitted_arrays = np.array_split(arr, num_sets)

# Wyświetl wynik
for subset in splitted_arrays:
    print(subset)

[1 2 3]
[4 5 6]
[7 8 9]


In [8]:
results[0]

ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: ultralytics.engine.results.Keypoints object
masks: None
names: {0: 'person'}
orig_img: array([[[ 72,  68,  44],
        [ 72,  68,  44],
        [ 72,  68,  44],
        ...,
        [ 13,  21,  12],
        [ 13,  21,  12],
        [ 13,  21,  12]],

       [[ 72,  68,  44],
        [ 72,  68,  44],
        [ 72,  68,  44],
        ...,
        [ 14,  21,  12],
        [ 13,  21,  12],
        [ 13,  21,  12]],

       [[ 72,  68,  44],
        [ 72,  68,  44],
        [ 72,  68,  44],
        ...,
        [ 14,  21,  12],
        [ 13,  21,  12],
        [ 13,  21,  12]],

       ...,

       [[193, 218, 240],
        [198, 222, 244],
        [204, 228, 249],
        ...,
        [193, 217, 238],
        [197, 220, 242],
        [197, 221, 242]],

       [[194, 218, 239],
        [200, 223, 245],
        [209, 232, 254],
        ...,
        [176, 200, 221],
        [

In [9]:
results[0].keypoints

ultralytics.engine.results.Keypoints object with attributes:

conf: tensor([[0.9935, 0.9738, 0.9691, 0.7886, 0.7753, 0.9978, 0.9975, 0.9896, 0.9874, 0.9865, 0.9849, 0.9993, 0.9992, 0.9980, 0.9976, 0.9823, 0.9793]])
data: tensor([[[299.3740, 279.9767,   0.9935],
         [309.5164, 270.6180,   0.9738],
         [290.0433, 269.8563,   0.9691],
         [323.5926, 275.0775,   0.7886],
         [277.1083, 275.1202,   0.7753],
         [344.9956, 336.4487,   0.9978],
         [259.5998, 336.7075,   0.9975],
         [361.3738, 415.5279,   0.9896],
         [242.9561, 419.2298,   0.9874],
         [366.5813, 494.8440,   0.9865],
         [237.1042, 497.0373,   0.9849],
         [327.6848, 484.6115,   0.9993],
         [274.6779, 484.2686,   0.9992],
         [320.3559, 596.6141,   0.9980],
         [274.5139, 596.1066,   0.9976],
         [311.6333, 689.2812,   0.9823],
         [296.4260, 702.7327,   0.9793]]])
has_visible: True
orig_shape: (793, 543)
shape: torch.Size([1, 17, 3])
xy: tenso

In [10]:
results[0].boxes

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0.])
conf: tensor([0.9170])
data: tensor([[224.0000, 232.0000, 383.0000, 769.0000,   0.9170,   0.0000]])
id: None
is_track: False
orig_shape: (793, 543)
shape: torch.Size([1, 6])
xywh: tensor([[303.5000, 500.5000, 159.0000, 537.0000]])
xywhn: tensor([[0.5589, 0.6311, 0.2928, 0.6772]])
xyxy: tensor([[224., 232., 383., 769.]])
xyxyn: tensor([[0.4125, 0.2926, 0.7053, 0.9697]])

In [40]:
import cv2
def plot_boxes(results, frame, num):
    xyxys = []
    confidences = []
    class_ids = []

    for result in results:
        boxes = result.boxes.cpu().numpy()
        xyxys = boxes.xyxy
        for xyxy in xyxys:
            x1 = int(xyxy[0].item())
            y1 = int(xyxy[1].item())
            x2 = int(xyxy[2].item())
            y2 = int(xyxy[3].item())
            new_frame = frame[y1:y2, x1:x2]
            num += 1
            cv2.imwrite(str(num) + '.png', new_frame)


In [42]:
import cv2
vidcap = cv2.VideoCapture('test1.webm')
success,image = vidcap.read()
count = 0
while success:
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = model(image, classes=[0,1])
    plot_boxes(results, image, count)
  
    success,image = vidcap.read()

0: 384x640 3 persons, 885.9ms
Speed: 5.4ms preprocess, 885.9ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 persons, 883.6ms
Speed: 3.2ms preprocess, 883.6ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 persons, 851.1ms
Speed: 3.0ms preprocess, 851.1ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 persons, 912.4ms
Speed: 4.0ms preprocess, 912.4ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 persons, 875.3ms
Speed: 3.0ms preprocess, 875.3ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 persons, 828.2ms
Speed: 10.2ms preprocess, 828.2ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 persons, 859.8ms
Speed: 2.0ms preprocess, 859.8ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 persons, 840.2ms
Speed: 2.0ms preprocess, 840.2ms inference, 3.0ms postprocess per 

KeyboardInterrupt: 

In [45]:
results = model('piesi.png', classes=[0,1])
image=cv2.imread('piesi.png')
plot_boxes(results, image, 20)


image 1/1 d:\magisterka\is_project\piesi.png: 352x640 11 persons, 786.1ms
Speed: 3.0ms preprocess, 786.1ms inference, 2.0ms postprocess per image at shape (1, 3, 352, 640)


In [18]:
results = model.track(source='test1.webm', save=True, imgsz=320, conf=0.3, classes=[0,1])



WARNING  inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (1/1221) d:\magisterka\is_project\test1.webm: 192x320 1 person, 295.0ms
video 1/1 (2/1221) d:\magisterka\is_project\test1.webm: 192x320 1 person, 288.0ms
video 1/1 (3/1221) d:\magisterka\is_project\test1.webm: 192x320 1 person, 274.0ms
video 1/1 (4/1221) d:\magisterka\is_project\test1.webm: 192x320 1 person, 275.0ms
video 1/1 (5/1221) d:\magisterka\is_project\test1.webm: 192x320 (no detections), 280.0ms
video 1/1 (6/1221) d:\magisterka\is_proje

[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted p